packages:
  - name: sample
    functions:
      - name: hello
        runtime: 'python:default'
        triggers:
          - name: trigger-hello
            sourceType: scheduler
            sourceDetails:
              cron: "0 * * * *"